### PR TITLE
Add bokeh climate zone map

### PR DESCRIPTION
**Pull request by alorenzo175**
Would be nice if it first displayed map.png while the bokeh map loads. Also need links to the KML, geojson, shapefiles

### CODE REVIEW

**Comment by alorenzo175** [comment]
@lboeman can you get this rendered on your branch?

**Comment by lboeman** [comment]
Rendered: https://lboeman.github.io/climatezones/

**Comment by wholmgren** [comment]
Nice! 

Maybe off topic for this PR... Is this based on counties? Looks weird that the distance from rocky mountains to the western edge of zone 4 is not constant. I guess almost everything about CO is questionable (not your fault)... Pueblo and Tucson in same zone rather than Pueblo and Denver does not make much sense. And Ft. Collins is with Chicago instead of Denver. Wouldn't have noticed any of this without this nice, precise map.

To me, the coloring makes region 7 look like a subset of region 5, which is both a nice thing to hint at and probably not what we're going for right now.

**Comment by alorenzo175** [comment]
Yes, it's based on counties that made it easy to capture the coasts and cascades. I just kind of roughly picked counties on the interior to match Justin's map. We can hand draw the interior boundaries to adjust. Some thoughts on adjustment:

-  maybe Region 3 should include the entire CA central valley? 
- how far north should 3 go?
- should region 1 around SF extend basically to the central valley?
- feels like most of the Appalachians should be part of one region
- should region 7 really extend up the Carolina coast?

**Comment by wholmgren** [comment]
> maybe Region 3 should include the entire CA central valley?

I'm ok with that.

> how far north should 3 go?

For simplicity, I'd stop at AZ/NM for now.

> feels like most of the Appalachians should be part of one region

Yeah, also could be true for Rockies and/or pacific crest too. Combine with elevation mask? Probably too much for now.

**Comment by alorenzo175** [comment]
@lboeman can you update with the latest?

Are we going to want this by the webinar tomorrow? or should we carefully adjust before publishing?

**Comment by wholmgren** [comment]
Let's merge today and make it better later.

**Comment by alorenzo175** [comment]
I think this is probably good enough for now.

**Pull request merged**
