### PR TITLE
Reorganize navigation, add Use Cases and Reference data stub pages

### PR DESCRIPTION
**Pull request by lboeman**
To make map placement and moving the mailchimp form easier I've moved their associated html to files in `_includes`. The Mailchimp form can be included on a page with `{% include mailchimp.html %}` and the reference data map with `{% include reference_map.html %}`.

### CODE REVIEW

**Comment by lboeman** [comment]
Moved  'Data Policies, Benchmark Forecasts, Metrics, Use Cases, and Reference data to a "Key Topics" menu dropdown, where the Key Topics menu item is only triggers the dropdown. This has the befinefit of not having to hover the menu to keep the dropdown open, and makes the mobile menu identical to the desktop site. 
If we'd rather have a 'Key Topics' landing page I can change it to be a link to that page, with a hover activated dropdown.

**Comment by wholmgren** [comment]
I see it's rendered at https://lboeman.github.io/

I'm ok without a key topics landing page. Can the menu (reliably) activate on hover and stick on click?

**Comment by lboeman** [comment]
I forgot to add a link to that. Thanks. It should now activate on hover, and stick on click.

**Comment by wholmgren** [comment]
The menu needs to be wider or the menu items need to be separated by more than "Benchmark" and "Forecasts"

**Comment by wholmgren** [comment]
looks to me. any other comments?

**Pull request merged**
