### PR TITLE
Definitions page

### PR DESCRIPTION
**Pull request by lboeman**
Moves definitions to their own page. Rendered at https://lboeman.github.io

### CODE REVIEW

**Comment by wholmgren** [comment]
add .swp to gitignore and remove file

**Comment by wholmgren** [comment]
can you search the repository for other links that need to be updated?

**Comment by wholmgren** [comment]
@cwhanse see https://lboeman.github.io/usecases/ and https://lboeman.github.io/definitions/ for proposed changes to definitions and use cases.

**Comment by cwhanse** [comment]
Definitions page looks good.  PR with a few more edits to usecases.md

**Comment by cwhanse** [comment]
Do you want me to submit my PR against master?  It wasn't merged into a0efb4a

**Comment by lboeman** [comment]
@cwhanse Sorry Cliff, I didn't get a notification about your PR to my fork.  Submitting against master would be great, Thank you.

**Comment by cwhanse** [comment]
@lboeman all good, I did it that way because I knew it was possible and wanted to figure out how to do it.

**Pull request merged**
